apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin-pod
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 5050
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin-pod
  template:
    metadata:
      labels:
        app: pgadmin-pod
    spec:
      containers:
      - name: -container
        image: dpage/pgadmin4
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: pgadmin4@pgadmin.org
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: False
        ports:
        - containerPort: 5050
          protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: shorturl-ingress
 annotations:
   kubernetes.io/ingress.class: "nginx"
   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: pgadmin.trustmacus.com
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: pgadmin-service
           port:
             number: 5050
